# Use a imagem oficial do PHP com Apache
FROM php:8.1-apache

# Instalar extensões do PHP necessárias
RUN docker-php-ext-install pdo pdo_mysql

# Copiar o código do aplicativo para o contêiner
COPY . /var/www/html

# Definir o diretório de trabalho
WORKDIR /var/www/html

# Instalar as dependências do Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer && \
    composer install --no-dev

# Configurar o Apache
RUN a2enmod rewrite
