version: 1
services:
  - type: web
    name: laravel-app
    env: php
    plan: free
    runtime: php8.2
    buildCommand: "composer install --no-dev"
    startCommand: "php artisan serve --host 0.0.0.0 --port 10000"
    envVars:
      - key: APP_KEY
        value: "base64:4WYZg+CA8L7eYsc/zKc3uJX33YiQ3h3G7b+nRV7Qr8c="
      - key: APP_ENV
        value: "production"
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: "https://your-app.onrender.com"  # Replace with your actual app URL
      - key: DB_CONNECTION
        value: "sqlite"
      - key: DB_DATABASE
        value: "/app/database/database.sqlite"  # Path to the SQLite file
